import { registerComponent } from "../react";
import { Button } from "./Button";
import { SpriteButton } from "./SpriteButton";
import { CloseButton } from "./CloseButton";
import { Checkbox } from "./Checkbox";
import { RadioButton } from "./RadioButton";
import { Dropdown } from "./Dropdown";
import { Listbox } from "./Listbox";
import { SlotButton } from "./SlotButton";
import { SlotButtonTable } from "./SlotButtonTable";
import { Input } from "./Input";
import { Slider } from "./Slider";
import { ProgressBar } from "./ProgressBar";
import { Switch } from "./Switch";
import { Label } from "./Label";
import { VFlow } from "./VFlow";
import { HFlow } from "./HFlow";
import { Titlebar } from "./Titlebar";
import { WindowFrame } from "./WindowFrame";
import { FixedWindowFrame } from "./FixedWindowFrame";
import { Tab } from "./Tab";
import { TabbedPane } from "./TabbedPane";
import { WellHeader } from "./WellHeader";
import { WellSection } from "./WellSection";
import { WellFold } from "./WellFold";
import { ShallowSection } from "./ShallowSection";
import { Indicator } from "./Indicator";
import { Labeled } from "./Labeled";
import { PinButton } from "./PinButton";
import { RadioButtons } from "./RadioButtons";
import { SectionGroup } from "./SectionGroup";
import { ScrollPane } from "./ScrollPane";
import { EmptyWidget } from "./EmptyWidget";
import { Frame } from "./Frame";
import { Table } from "./Table";
import { Line } from "./Line";
import { Sprite } from "./Sprite";
import { Camera } from "./Camera";
import { Minimap } from "./Minimap";
import { EntityPreview } from "./EntityPreview";

export * from "./Button";
export * from "./SpriteButton";
export * from "./CloseButton";
export * from "./Checkbox";
export * from "./RadioButton";
export * from "./Dropdown";
export * from "./Listbox";
export * from "./SlotButton";
export * from "./SlotButtonTable";
export * from "./Input";
export * from "./Slider";
export * from "./ProgressBar";
export * from "./Switch";
export * from "./Label";
export * from "./VFlow";
export * from "./HFlow";
export * from "./Titlebar";
export * from "./WindowFrame";
export * from "./FixedWindowFrame";
export * from "./Tab";
export * from "./TabbedPane";
export * from "./WellHeader";
export * from "./WellSection";
export * from "./WellFold";
export * from "./ShallowSection";
export * from "./Indicator";
export * from "./Labeled";
export * from "./PinButton";
export * from "./RadioButtons";
export * from "./SectionGroup";
export * from "./ScrollPane";
export * from "./EmptyWidget";
export * from "./Frame";
export * from "./Table";
export * from "./Line";
export * from "./Sprite";
export * from "./Camera";
export * from "./Minimap";
export * from "./EntityPreview";

// Auto-register library components for exact component names in Strace / React Profiling
registerComponent("Button", Button);
registerComponent("SpriteButton", SpriteButton);
registerComponent("CloseButton", CloseButton);
registerComponent("Checkbox", Checkbox);
registerComponent("RadioButton", RadioButton);
registerComponent("Dropdown", Dropdown);
registerComponent("Listbox", Listbox);
registerComponent("SlotButton", SlotButton);
registerComponent("SlotButtonTable", SlotButtonTable);
registerComponent("Input", Input);
registerComponent("Slider", Slider);
registerComponent("ProgressBar", ProgressBar);
registerComponent("Switch", Switch);
registerComponent("Label", Label);
registerComponent("VFlow", VFlow);
registerComponent("HFlow", HFlow);
registerComponent("Titlebar", Titlebar);
registerComponent("WindowFrame", WindowFrame);
registerComponent("FixedWindowFrame", FixedWindowFrame);
registerComponent("Tab", Tab);
registerComponent("TabbedPane", TabbedPane);
registerComponent("WellHeader", WellHeader);
registerComponent("WellSection", WellSection);
registerComponent("WellFold", WellFold);
registerComponent("ShallowSection", ShallowSection);
registerComponent("Indicator", Indicator);
registerComponent("Labeled", Labeled);
registerComponent("PinButton", PinButton);
registerComponent("RadioButtons", RadioButtons);
registerComponent("SectionGroup", SectionGroup);
registerComponent("ScrollPane", ScrollPane);
registerComponent("EmptyWidget", EmptyWidget);
registerComponent("Frame", Frame);
registerComponent("Table", Table);
registerComponent("Line", Line);
registerComponent("Sprite", Sprite);
registerComponent("Camera", Camera);
registerComponent("Minimap", Minimap);
registerComponent("EntityPreview", EntityPreview);
